#!/usr/bin/env bash
source .env

if [ ! -f "./server" ]; then
    go build server.go
fi

parallel ::: "./server" "browser-sync start --no-notify --port ${DEVPORT} --browser 'firefox' --proxy 'localhost:${PORT}' --files './**'"
